# Min-Max Scaling

## 1. What is Min-Max Scaling?

**Min-Max Scaling** is a Feature Scaling technique used to transform numerical features into a specific range.

The most common range is:

$$
[0,1]
$$

Unlike Standardization, Min-Max Scaling does **not** make the mean equal to 0 or the standard deviation equal to 1.

### Formula

$$
x' = \frac{x-x_{min}}{x_{max}-x_{min}}
$$

Where:

- $x$ = original value
- $x_{min}$ = minimum value of the feature
- $x_{max}$ = maximum value of the feature
- $x'$ = scaled value

After scaling:

- Minimum value → 0
- Maximum value → 1
- Other values → between 0 and 1

## 3. Why Do We Use Min-Max Scaling?

Different features can have very different scales.

For example:

- Age → 18–60
- Salary → 5,000–100,000
- Area → 50–10,000

Min-Max Scaling transforms them into a common range, usually:

[0, 1]

This makes the features comparable in scale.

## 4. Dataset

For practice, we use the **Breast Cancer Dataset** provided by Scikit-learn.

**Scikit-learn (`sklearn`)** is a Python library for Machine Learning.

It provides tools for:

- Data preprocessing
- Feature scaling
- Classification
- Regression
- Clustering
- Model evaluation

In [3]:
from sklearn.datasets import load_breast_cancer
import pandas as pd

data = load_breast_cancer(as_frame=True)

df = data.frame
df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,1

### `load_breast_cancer()`

`load_breast_cancer()` is a function that loads a built-in Breast Cancer dataset from Scikit-learn.

### `as_frame=True`

`as_frame=True` tells Scikit-learn to return the dataset as a **Pandas DataFrame**.

In [4]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
mean radius,569.0,14.127292,3.524049,6.981000,11.700000,13.370000,15.780000,28.11000
mean texture,569.0,19.289649,4.301036,9.710000,16.170000,18.840000,21.800000,39.28000
mean perimeter,569.0,91.969033,24.298981,43.790000,75.170000,86.240000,104.100000,188.50000
mean area,569.0,654.889104,351.914129,143.500000,420.300000,551.100000,782.700000,2501.00000
mean smoothness,569.0,0.096360,0.014064,0.052630,0.086370,0.095870,0.105300,0.16340
mean compactness,569.0,0.104341,0.052813,0.019380,0.064920,0.092630,0.130400,0.34540
mean concavity,569.0,0.088799,0.079720,0.000000,0.029560,0.061540,0.130700,0.42680
mean concave points,569.0,0.048919,0.038803,0.000000,0.020310,0.033500,0.074000,0.20120
mean symmetry,569.0,0.181162,0.027414,0.106000,0.161900,0.179200,0.195700,0.30400
mean fractal dimension,569.0,0.062798,0.007060,0.049960,0.057700,0.061540,0.066120,0.09744
radius error,569.0,0.405172,0.277313,0.111500,0.232400,0.324200,0.478900,2.87300
texture error,569.0,1.216853,0.551648,0.360200,0.833900,1.108000,1.474000,4.88500
perimeter error,569.0,2.866059,2.021855,0.757000,1.606000,2.287000,3.357000,21.98000
area error,569.0,40.337079,45.491006,6.802000,17.850000,24.530000,45.190000,542.20000
smoothness error,569.0,0.007041,0.003003,0.001713,0.005169,0.006380,0.008146,0.03113
compactness error,569.0,0.025478,0.017908,0.002252,0.013080,0.020450,0.032450,0.13540
concavity error,569.0,0.031894,0.030186,0.000000,0.015090,0.025890,0.042050,0.39600
concave points error,569.0,0.011796,0.006170,0.000000,0.007638,0.010930,0.014710,0.05279
symmetry error,569.0,0.020542,0.008266,0.007882,0.015160,0.018730,0.023480,0.07895
fractal dimension error,569.0,0.003795,0.002646,0.000895,0.002248,0.003187,0.004558,0.02984
worst radius,569.0,16.269190,4.833242,7.930000,13.010000,14.970000,18.790000,36.04000
worst texture,569.0,25.677223,6.146258,12.020000,21.080000,25.410000,29.720000,49.54000
worst perimeter,569.0,107.261213,33.602542,50.410000,84.110000,97.660000,125.400000,251.20000
worst area,569.0,880.583128,569.356993,185.200000,515.300000,686.500000,1084.000000,4254.00000
worst smoothness,569.0,0.132369,0.022832,0.071170,0.116600,0.131300,0.146000,0.22260
worst compactness,569.0,0.254265,0.157336,0.027290,0.147200,0.211900,0.339100,1.05800
worst concavity,569.0,0.272188,0.208624,0.000000,0.114500,0.226700,0.382900,1.25200
worst concave points,569.0,0.114606,0.065732,0.000000,0.064930,0.099930,0.161400,0.29100
worst symmetry,569.0,0.290076,0.061867,0.156500,0.250400,0.282200,0.317900,0.66380
worst fractal dimension,569.0,0.083946,0.018061,0.055040,0.071460,0.080040,0.092080,0.20750
target,569.0,0.627417,0.483918,0.000000,0.000000,1.000000,1.000000,1.00000

## 7. Separating Features and Target

Machine Learning datasets usually contain:

- **Features (`X`)** → input variables
- **Target (`y`)** → the value we want the model to predict.

In [5]:
x = df.drop("target", axis=1)
y = df["target"]

Here:

- `X` contains the 30 features.
- `y` contains the target.

Feature Scaling is applied to **X**, not usually to **y**.

## 8. MinMaxScaler

Scikit-learn provides `MinMaxScaler` to perform Min-Max Scaling.

In [7]:
from sklearn.preprocessing import MinMaxScaler

We create a scaler object:

At this point, scaling has **not happened yet**.

We have only created the scaler.

The default range is:

[0, 1]

In [8]:
scaler = MinMaxScaler()

## 9. Applying Min-Max Scaling

We can apply Min-Max Scaling using `fit_transform()`.

In [9]:
x_minmax = scaler.fit_transform(x)

`fit_transform()` combines two operations.

### `fit()`

The scaler finds the:

- Minimum value
- Maximum value

of **each feature independently**.

### `transform()`

The scaler uses these values to transform each feature using:

$$
x' = \frac{x-x_{min}}{x_{max}-x_{min}}
$$

Therefore:

```python
scaler.fit_transform(X)

## 10. Checking the Result

We can inspect the scaled data:

In [10]:
x_minmax[:5]

array([[0.52103744, 0.0226581 , 0.54598853, 0.36373277, 0.59375282,
        0.7920373 , 0.70313964, 0.73111332, 0.68636364, 0.60551811,
        0.35614702, 0.12046941, 0.3690336 , 0.27381126, 0.15929565,
        0.35139844, 0.13568182, 0.30062512, 0.31164518, 0.18304244,
        0.62077552, 0.14152452, 0.66831017, 0.45069799, 0.60113584,
        0.61929156, 0.56861022, 0.91202749, 0.59846245, 0.41886396],
       [0.64314449, 0.27257355, 0.61578329, 0.50159067, 0.28987993,
        0.18176799, 0.20360825, 0.34875746, 0.37979798, 0.14132266,
        0.15643672, 0.08258929, 0.12444047, 0.12565979, 0.11938675,
        0.08132304, 0.0469697 , 0.25383595, 0.08453875, 0.0911101 ,
        0.60690146, 0.30357143, 0.53981772, 0.43521431, 0.34755332,
        0.15456336, 0.19297125, 0.63917526, 0.23358959, 0.22287813],
       [0.60149557, 0.3902604 , 0.59574321, 0.44941676, 0.51430893,
        0.4310165 , 0.46251172, 0.63568588, 0.50959596, 0.21124684,
        0.22962158, 0.09430251, 0.18037035, 0.16292179, 0.15083115,
        0.2839547 , 0.09676768, 0.38984656, 0.20569032, 0.12700551,
        0.55638563, 0.36007463, 0.50844166, 0.37450845, 0.48358978,
        0.38537513, 0.35974441, 0.83505155, 0.40370589, 0.21343303],
       [0.2100904 , 0.36083869, 0.23350149, 0.10290562, 0.81132075,
        0.81136127, 0.5656045 , 0.52286282, 0.77626263, 1.        ,
        0.13909107, 0.17587518, 0.12665504, 0.03815479, 0.25145324,
        0.54321507, 0.14295455, 0.35366547, 0.72814769, 0.28720479,
        0.24831021, 0.38592751, 0.24134668, 0.09400806, 0.9154725 ,
        0.8140117 , 0.54864217, 0.88487973, 1.        , 0.77371114],
       [0.62989256, 0.15657761, 0.63098611, 0.4892895 , 0.43035118,
        0.34789277, 0.46391753, 0.51838966, 0.37828283, 0.1868155 ,
        0.2338222 , 0.09306489, 0.2205626 , 0.16368757, 0.33235884,
        0.16791841, 0.14363636, 0.3570752 , 0.13617943, 0.14579965,
        0.51974386, 0.1239339 , 0.50694756, 0.34157491, 0.4373638 ,
        0.17241513, 0.31948882, 0.55841924, 0.15750049, 0.14259478]])

In [12]:
x_minmax.min(axis=0)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

The minimum value of each feature should be approximately **0**.

In [13]:
x_minmax.max(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

The maximum value of each feature should be approximately **1**.

In [ ]:
scaler.data_min_
# to see the min values

array([6.981e+00, 9.710e+00, 4.379e+01, 1.435e+02, 5.263e-02, 1.938e-02,
       0.000e+00, 0.000e+00, 1.060e-01, 4.996e-02, 1.115e-01, 3.602e-01,
       7.570e-01, 6.802e+00, 1.713e-03, 2.252e-03, 0.000e+00, 0.000e+00,
       7.882e-03, 8.948e-04, 7.930e+00, 1.202e+01, 5.041e+01, 1.852e+02,
       7.117e-02, 2.729e-02, 0.000e+00, 0.000e+00, 1.565e-01, 5.504e-02])

In [16]:
scaler.data_max_
# to see the max values

array([2.811e+01, 3.928e+01, 1.885e+02, 2.501e+03, 1.634e-01, 3.454e-01,
       4.268e-01, 2.012e-01, 3.040e-01, 9.744e-02, 2.873e+00, 4.885e+00,
       2.198e+01, 5.422e+02, 3.113e-02, 1.354e-01, 3.960e-01, 5.279e-02,
       7.895e-02, 2.984e-02, 3.604e+01, 4.954e+01, 2.512e+02, 4.254e+03,
       2.226e-01, 1.058e+00, 1.252e+00, 2.910e-01, 6.638e-01, 2.075e-01])

In [17]:
scaler.data_range_
# to see the range

array([2.11290e+01, 2.95700e+01, 1.44710e+02, 2.35750e+03, 1.10770e-01,
       3.26020e-01, 4.26800e-01, 2.01200e-01, 1.98000e-01, 4.74800e-02,
       2.76150e+00, 4.52480e+00, 2.12230e+01, 5.35398e+02, 2.94170e-02,
       1.33148e-01, 3.96000e-01, 5.27900e-02, 7.10680e-02, 2.89452e-02,
       2.81100e+01, 3.75200e+01, 2.00790e+02, 4.06880e+03, 1.51430e-01,
       1.03071e+00, 1.25200e+00, 2.91000e-01, 5.07300e-01, 1.52460e-01])

## 11. Changing the Feature Range

The default range of `MinMaxScaler` is:

[0, 1]

However, we can choose another range using `feature_range`.

In [18]:
scaler = MinMaxScaler(feature_range=(-1,1))
x_minmax = scaler.fit_transform(x)

In [19]:
x_minmax

array([[ 0.04207487, -0.9546838 ,  0.09197706, ...,  0.82405498,
         0.1969249 , -0.16227207],
       [ 0.28628899, -0.45485289,  0.23156658, ...,  0.27835052,
        -0.53282082, -0.55424374],
       [ 0.20299115, -0.2194792 ,  0.19148642, ...,  0.67010309,
        -0.19258821, -0.57313394],
       ...,
       [-0.08949785,  0.24247548, -0.10842374, ..., -0.02542955,
        -0.74255864, -0.69618261],
       [ 0.28912869,  0.32702063,  0.33107594, ...,  0.82130584,
        -0.00571654, -0.09536928],
       [-0.92626248,  0.00304363, -0.94292032, ..., -1.        ,
        -0.48511729, -0.79863571]])

Now the values will be scaled to:

[-1, 1]

## 14. Min-Max Scaling and Outliers

Min-Max Scaling is sensitive to **outliers**.

For example:

10, 12, 15, 18, 20, 1000

Here, `1000` is an extreme value.

Since Min-Max Scaling uses the minimum and maximum values, `1000` becomes the maximum.

This can compress most of the other values into a small part of the [0, 1] range.

## 15. Standardization vs Min-Max Scaling

### Standardization

Uses:

$$
z = \frac{x-\mu}{\sigma}
$$

Based on:

- Mean
- Standard Deviation

Result:

- Mean ≈ 0
- Standard Deviation ≈ 1
- No fixed range

Using:

`StandardScaler()`

### Min-Max Scaling

Uses:

$$
x' = \frac{x-x_{min}}{x_{max}-x_{min}}
$$

Based on:

- Minimum
- Maximum

Result:

- Minimum = 0
- Maximum = 1
- Usually between 0 and 1

Using:

`MinMaxScaler()`

## 16. Data Leakage

When working with Machine Learning models, we should **not fit the scaler on the entire dataset before splitting it**.

### Incorrect

```python
scaler.fit_transform(X)

X_train = ...
X_test = ...